image: maven:3.8.2-jdk-11

stages:          # List of stages for jobs, and their order of execution
  - test
  - SonarCheck
  - DeployContainer

variables:
  CI_REGISTRY_IMAGE_DEPENDENCIES: "${CI_REGISTRY_IMAGE}/skeleton_dependencies"
  CI_REGISTRY_IMAGE_RELEASE: "${CI_REGISTRY_IMAGE}/maven4skeleton"
  DOCKER_HOST: docker.uibk.ac.at:443
  DOCKER_TLS_CERTDIR: "/certs"

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."
    - mvn test
  when: manual

sonarqube-check:
  stage: SonarCheck
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/code/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo Running sonar analysis for ${SONAR_PROJECT_KEY}
    - mvn -Dsonar.projectKey=${SONAR_PROJECT_KEY} verify sonar:sonar
  allow_failure: true
  when: manual
  
release_container:
  stage: DeployContainer
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
#  before_script:
#    - echo ${CI_REGISTRY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
  script:
    - echo $CI_COMMIT_TAG
    - docker build --target release --tag $CI_REGISTRY_IMAGE_RELEASE:latest --tag $CI_REGISTRY_IMAGE_RELEASE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE_RELEASE:latest
    - docker push $CI_REGISTRY_IMAGE_RELEASE:$CI_COMMIT_TAG
  only:
   - tags
